name: Carthage
schemes:
  libllbuild:
    build:
      targets:
        libllbuild: build
  llbuildBasic:
    build:
      targets:
        llbuildBasic: build
  llbuildBuildSystem:
    build:
      targets:
        llbuildBuildSystem: build
  llbuildCore:
    build:
      targets:
        llbuildCore: build
  llbuildSwift:
    build:
      targets:
        llbuildSwift: build
  llvmDemangle:
    build:
      targets:
        llvmDemangle: build
  llvmSupport:
    build:
      targets:
        llvmSupport: build 
targets:
  llvmDemangle:
    settings:
      HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/lib/llvm/Demangle/include"        
    sources:
      - path: lib/llvm/Demangle
        includes:
          - "**/*.cpp"
    type: framework
    platform: macOS  
  llvmSupport:
    dependencies:
      - target: llvmDemangle
    settings:
      HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/lib/llvm/Support/include"        
        - "$(SRCROOT)/lib/llvm/Demangle/include"
      OTHER_LDFLAGS:
        - "-lncurses"
    sources:
      - path: lib/llvm/Support
        includes:
          - "**/*.cpp"
    type: framework
    platform: macOS
  llbuildBasic:
    dependencies:
      - target: llvmSupport
      - target: llvmDemangle
    settings:
      HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/lib/Basic/include"
        - "$(SRCROOT)/lib/llvm/Support/include"
        - "$(SRCROOT)/lib/llvm/Demangle/include"
    sources:
      - path: lib/Basic
        includes:
          - "**/*.{cpp}"
    type: framework
    platform: macOS
  llbuildCore:
    dependencies:
      - target: llbuildBasic
      - target: llvmSupport
      - target: llvmDemangle
    settings:
      HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/lib/Core/include"
        - "$(SRCROOT)/lib/Basic/include"
        - "$(SRCROOT)/lib/llvm/Support/include"
        - "$(SRCROOT)/lib/llvm/Demangle/include"
      OTHER_LDFLAGS:
        - "-lsqlite3"
    sources:
      - path: lib/Core
        includes:
          - "**/*.{cpp}"
    type: framework
    platform: macOS
  llbuildBuildSystem:
    dependencies:
      - target: llbuildCore
      - target: llbuildBasic
      - target: llvmSupport
      - target: llvmDemangle
    settings:
      HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/lib/BuildSystem/include"
        - "$(SRCROOT)/lib/Core/include"
        - "$(SRCROOT)/lib/Basic/include"
        - "$(SRCROOT)/lib/llvm/Support/include"
        - "$(SRCROOT)/lib/llvm/Demangle/include"
    sources:
      - path: lib/BuildSystem
        includes:
          - "**/*.{cpp}"
    type: framework
    platform: macOS
  libllbuild:
    dependencies:
      - target: llbuildBuildSystem
      - target: llbuildCore
      - target: llbuildBasic
      - target: llvmSupport
      - target: llvmDemangle
    settings:
      HEADER_SEARCH_PATHS:
          - "$(SRCROOT)/products/libllbuild/include"
          - "$(SRCROOT)/lib/BuildSystem/include"
          - "$(SRCROOT)/lib/Core/include"
          - "$(SRCROOT)/lib/Basic/include"
          - "$(SRCROOT)/lib/llvm/Support/include"
          - "$(SRCROOT)/lib/llvm/Demangle/include"
      MODULEMAP_FILE:
        - $(SRCROOT)/products/libllbuild/include/module.modulemap
    sources:
      - path: products/libllbuild
        includes:
          - "**/*.cpp"
          - "include/llbuild/*.h"
          - "include/module.modulemap"
    type: framework
    platform: macOS
  llbuildSwift:
    dependencies:
      - target: libllbuild
      - target: llbuildBuildSystem
      - target: llbuildCore
      - target: llbuildBasic
      - target: llvmSupport
      - target: llvmDemangle
    settings:
      INFOPLIST_FILE: plist/Info.plist
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    sources:
      - path: products/llbuildSwift
        includes:
          - "**/*.swift"
        excludes:
          - "**/*.txt"
    type: framework
    platform: macOS
